<?xml version="1.0" encoding="UTF-8"?><record_update table="sys_ui_message">
    <sys_ui_message action="INSERT_OR_UPDATE">
        <application/>
        <code/>
        <commented_message/>
        <key>GlobalToolsRecordWriteValidate_400_039_ErrorDetail</key>
        <language>en</language>
        <message>The reference field validation for field "{0}" on reference table "{3}" for value "{1}" failed, the referenced record {2} was created.</message>
        <sys_class_name>sys_ui_message</sys_class_name>
        <sys_created_by>tom.hauri</sys_created_by>
        <sys_created_on>2024-04-24 06:57:45</sys_created_on>
        <sys_id>b761c0c11b3d421030d6fdd49b4bcbf8</sys_id>
        <sys_mod_count>1</sys_mod_count>
        <sys_name>GlobalToolsRecordWriteValidate_400_039_ErrorDetail</sys_name>
        <sys_package display_value="Global Tools" source="a39b8f3697816110b434f5f3a253af25">a39b8f3697816110b434f5f3a253af25</sys_package>
        <sys_policy/>
        <sys_scope display_value="Global Tools">a39b8f3697816110b434f5f3a253af25</sys_scope>
        <sys_update_name>sys_ui_message_b761c0c11b3d421030d6fdd49b4bcbf8</sys_update_name>
        <sys_updated_by>tom.hauri</sys_updated_by>
        <sys_updated_on>2024-04-24 06:58:41</sys_updated_on>
    </sys_ui_message>
</record_update>
